log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanPipeline", "VulkanTransferPass"]

[window]
name = ""
width = 400
height = 170
resizable = false
vsync = true
