kind = "raster"
depth = true

[blend]
enabled = true

[vertex]
positions = "vec3"
normals = "vec3"


# ====================================================================================================
# ====================================================================================================
# ======================================          PASS          ======================================
# ====================================================================================================
# ====================================================================================================

[pass.vertex]
index = 0
shader = "shaders:/base/3D/color/color.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/3D/color/color.frag.spv"

# ====================================================================================================
# ====================================================================================================
# ====================================          UNIFORM          =====================================
# ====================================================================================================
# ====================================================================================================

[set.camera.uniform.camera]
binding = 1
size = 204

[set.object.uniform.world]
binding = 0
size = 64

[set.object.uniform.material]
binding = 2
size = 4
