kind = "compute"

[local-groups]
x = 32
y = 32
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/compose/compose.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

[set.global.texture.positions]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

[set.global.texture.normals]
binding     = 2
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

[set.global.texture.binormals]
binding     = 3
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

[set.global.texture.albedo]
binding     = 4
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

[set.global.texture.depth]
binding     = 5
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

[set.global.texture.materialID]
binding     = 6
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "near"
mag-filter  = "near"
min-filter  = "near"
anisotropy  = false

[set.global.texture.shadowMaps]
binding     = 7
sampler     = 8
addressMode = "clamp-edge"
mipmap      = "linear"
anisotropy  = false

# ====================================================================================================
# ====================================================================================================
# ====================================          UNIFORM          =====================================
# ====================================================================================================
# ====================================================================================================

[set.global.uniform.camera]
binding = 9
size    = 204

# ====================================================================================================
# ====================================================================================================
# ====================================          BUFFERS          =====================================
# ====================================================================================================
# ==================================================================================================== 

[set.global.buffer.material]
binding = 10 

[set.global.buffer.direction_light]
binding = 11

[set.global.buffer.point_light]
binding = 12

[set.global.buffer.spot_light]
binding = 13

# ====================================================================================================
# ====================================================================================================
# =======================================          PC          =======================================
# ====================================================================================================
# ====================================================================================================

# [push.test]
# offset = 0
# size = 4
