[local-groups]
x = 32
y = 32
z = 1

[pass.compute]
index = 0
shader = "shaders:/base/3D/compose/compose.comp.spv"

[storage-texture.output]
binding = 0

[texture.positions]
binding = 1
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = false

[texture.normals]
binding = 2
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = false

[texture.binormals]
binding = 3
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = false

[texture.albedo]
binding = 4
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = false

[texture.depth]
binding = 5
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = false

[texture.materialID]
binding = 6
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "near"
mag-filter = "near"
min-filter = "near"
anisotropy = false

[buffer.material]
binding = 7

[uniform.camera]
binding = 8
size = 204
