kind = "raster"
depth = true

[blend]
enabled = false

[vertex]
positions = "vec3"
normals = "vec3"
tex_uv = "vec2"


# ====================================================================================================
# ====================================================================================================
# ======================================          PASS          ======================================
# ====================================================================================================
# ====================================================================================================


[pass.vertex]
index = 0
shader = "shaders:/base/3D/texture/texture.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/3D/texture/texture.frag.spv"


# ====================================================================================================
# ====================================================================================================
# ====================================          UNIFORM          =====================================
# ====================================================================================================
# ====================================================================================================

[set.camera.uniform.camera]
binding = 0
size = 204

[set.object.uniform.world]
binding = 0
size = 64

[set.object.uniform.material]
binding = 1
size = 4

[set.object.texture.albedo]
binding = 2
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = true
