depth = true

[blend]
enabled = true

[vertex]
positions = "vec3"
normals = "vec3"
tex_uv = "vec2"

[pass.vertex]
index = 0
shader = "shaders:/base/3D/texture/texture.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/3D/texture/texture.frag.spv"

[uniform.world]
binding = 0
size = 64

[uniform.camera]
binding = 1
size = 192

[uniform.color]
binding = 2
size = 16

[texture.albedo]
binding = 3
kind = "albedo"
addressMode = "clamp-edge"
mipmap = "linear"
anisotropy = true
