log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanTransferPass"]

[window]
name = "Ymir is the Best !"
width = 1280
height = 720
resizable = true

[vulkan]
version = 13
anisotropy = true
image-count = 1
vsync = true

[timer]
fps = 120
ips = 30
interactive = false
