#log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin"]

[window]
name = "Ymir is the Best !"
width = 1920
height = 1080
resizable = false
vsync = true

[vulkan]
version = 13
anisotropy = true
depth = true
msaa = false
msaa-samples = 16

[timer]
fps = -1
ips = 30
interactive = false
