#log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin"]

[window]
name = "Ymir is the Best !"
width = 1920
height = 1080
resizable = true

[vulkan]
version = 13
anisotropy = true
image-count = 3
vsync = true

[timer]
fps = 48
ips = 30
interactive = false
