#log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin"]

[window]
name = "Ymir is the Best !"
width = 1280
height = 768
resizable = true
vsync = true

[vulkan]
version = 12
anisotropy = true
depth = true
msaa = true
msaa-samples = 16

[timer]
fps = -1
ips = 30
interactive = false
