log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanPipeline"]

[window]
name = "Ymir is the Best !"
width = 1280
height = 720
resizable = true

[vulkan]
version = 13
anisotropy = true
image-count = 3
vsync = false

[timer]
fps = -1
ips = 30
interactive = false
