kind = "raster"
depth = true

[blend]
enabled = true

[vertex]
positions = "vec2"

[pass.vertex]
index = 0
shader = "shaders:/base/2D/color/color.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/2D/color/color.frag.spv"


[push.window]
offset = 0
size = 8

[set.object.uniform.world]
binding = 0
size = 36
